version: '3'

services:
  
    react-app:
        build: ./react-frontend
        ports: 
            - 3001:3000
        depends_on: 
            - nest-api

    nest-api: 
        build: ./nest-api 
        ports: 
            - 3000:3000
