version: "3"
services:
  rest-api:
    build: nest-api
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3000:3000
    volumes:
      - ./nest-api:/home/node/app
  react-frontend:
    build: react-frontend
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3001:3000
    volumes:
      - ./react-frontend:/home/node/app