version: '3'

services:
  
    react-app:
        build: ./nest-api
        entrypoint: ./nest-api/.docker/entrypoint.sh
        ports: 
        - 3001:3000
        volumes:
        - .:/home/node/app

    nest-api:
        build: ./react-frontend
        entrypoint: ./nest-api/.docker/entrypoint.sh
        ports: 
          - 3000:3000
        volumes:
          - .:/home/node/app