version: '3'

services:
  
    react-app:
        build: ./nest-api
        entrypoint: .docker/entrypoint.sh
        ports: 
            - 3001:3000
        volumes:
            - ./react-frontend:/home/node/app
        depends_on: 
            - nest-api

    nest-api:
        build: ./react-frontend
        entrypoint: .docker/entrypoint.sh
        ports: 
          - 3000:3000
        volumes:
          - ./nest-api:/home/node/app